apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  accessModes:
  - ReadWriteOnce
  #- ReadWriteMany
  #- ReadOnlyMany
  hostPath:
    path: /opt/pvdemo
    type: DircetoryOrCreate
  #nfs:
    #path: /data/volume-demo
    #server: 192.168.1.1
  capacity:
    storage: 5Gi
